{% set name = "bleak" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bleak-{{ version }}.tar.gz
  sha256: a8043fc0f3af1a00a84963824195463ca39789ae4f6804d3d7b1423e6083254a

build:
  entry_points:
    - bleak-lescan=bleak:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # Mac Os X is currently not working as - pyobjc-framework-libdispatch is missing on conda-forge
  skip: true  # [osx]

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - bleak-winrt >=1.1.1  # [win]
    - dbus-fast  # [linux]
    - pyobjc-core  # [osx]
    - pyobjc-framework-corebluetooth  # [osx]
    - pyobjc-framework-libdispatch  # [osx]
    - python
    - typing-extensions >=4.2.0
    - async-timeout

test:
  imports:
    - bleak
  commands:
    - bleak-lescan --help
    - pip check  # [not win]
  requires:
    - pip

about:
  home: https://github.com/hbldh/bleak
  summary: Bluetooth Low Energy platform Agnostic Klient
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - carlodri
    - jan-janssen
    - tdido
