{% set name = "bleak" %}
{% set version = "0.22.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bleak-{{ version }}.tar.gz
  sha256: 3149c3c19657e457727aa53d9d6aeb89658495822cd240afd8aeca4dd09c045c

build:
  entry_points:
    - bleak-lescan=bleak:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # Mac Os X is currently not working as - pyobjc-framework-libdispatch is missing on conda-forge
  skip: true  # [osx]

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - bleak-winrt >=1.1.1  # [win]
    - dbus-fast  # [linux]
    - pyobjc-core  # [osx]
    - pyobjc-framework-corebluetooth  # [osx]
    - pyobjc-framework-libdispatch  # [osx]
    - python
    - typing-extensions >=4.2.0
    - async-timeout

test:
  imports:
    - bleak
  commands:
    - pip check
    - bleak-lescan --help
  requires:
    - pip

about:
  home: https://github.com/hbldh/bleak
  summary: Bluetooth Low Energy platform Agnostic Klient
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - tdido
