{% set name = "bleak" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bleak-{{ version }}.tar.gz
  sha256: a549f43e3c5d8de464c72b4b905534c3f4781746e9815ecd531b7255de2e19c7

build:
  entry_points:
    - bleak-lescan=bleak:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  # Mac Os X is currently not working as - pyobjc-framework-libdispatch is missing on conda-forge
  skip: true  # [osx]

requirements:
  host:
    - pip
    - python
  run:
    - bleak-winrt >=1.1.1  # [win]
    - dbus-next  # [linux]
    - pyobjc-core  # [osx]
    - pyobjc-framework-corebluetooth  # [osx]
    - pyobjc-framework-libdispatch  # [osx]
    - python
    - typing-extensions >=4.2.0
    - async-timeout

test:
  imports:
    - bleak
  commands:
    - pip check
    - bleak-lescan --help
  requires:
    - pip

about:
  home: https://github.com/hbldh/bleak
  summary: Bluetooth Low Energy platform Agnostic Klient
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
