schema_version: 1

context:
  name: bleak
  version: 0.22.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/bleak-${{ version }}.tar.gz
  sha256: 73c2e774c22345e170d36a55a9dd06f6633c88b4184d5f86140a8224f12282d4

build:
  # Mac Os X is currently not working as - pyobjc-framework-libdispatch is missing on conda-forge
  number: 1
  skip: osx
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - bleak-lescan=bleak:cli

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - if: win
      then: bleak-winrt >=1.1.1
    - if: linux
      then: dbus-fast
    - if: osx
      then: pyobjc-core
    - if: osx
      then: pyobjc-framework-corebluetooth
    - if: osx
      then: pyobjc-framework-libdispatch
    - python
    - typing-extensions >=4.2.0
    - async-timeout

tests:
  - python:
      imports:
        - bleak
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - bleak-lescan --help

about:
  summary: Bluetooth Low Energy platform Agnostic Klient
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/hbldh/bleak

extra:
  recipe-maintainers:
    - jan-janssen
    - tdido
